rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - rbx-head
  - rbx-head-d19
gemfile:
  - Gemfile
  - gemfiles/Gemfile-3.0
  - gemfiles/Gemfile-3.1
  - gemfiles/Gemfile-3.2
  - gemfiles/Gemfile-4.0
